plugins {
    id 'application'
    id 'com.gradleup.shadow' version '9.+'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.google.code.gson:gson:${project.deps_gson}"
    implementation "org.xerial:sqlite-jdbc:${project.deps_sqlite_jdbc}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 25 
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'hibiscvs.modbone.Main'
    }
    from ('LICENSE')
}

shadowJar {
    filesMatching('META-INF/services/**') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}

application {
    mainClass = 'hibiscvs.modbone.Main'
}
