plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.google.code.gson:gson:${project.deps_gson}"
    implementation "org.xerial:sqlite-jdbc:${project.deps_sqlite_jdbc}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 25 
    }
}

application {
    mainClass = 'hibiscvs.modbone.Main'
}
